### ISSUE TITLE
Can't build website when there's an index.md file in level 1 directory in content

### ISSUE THREAD

**Issue by kamoshi** [Keats/gutenberg#2101]
# Bug Report

## Environment

Zola version: v0.17.0  (Linux)

## Expected Behavior
When we have a content directory of the following structure:
```
content
| _index.md
| hello.md
| world.md
> subdir
   | index.md
   | asset.png
```
The site should build normally and there should be a single page located at `/subdir/`.

## Current Behavior
The site fails to be built with the following error:
```
Error: Failed to build the site
Error: We can't have a page called `index.md` in the same folder as an index section in "/home/user/zola-site/content"
```

## Step to reproduce
1. Create a website which has a subdirectory inside `content` and add `index.md` page into that subdirectory.
2. Try building the website with `zola serve`

**Comment by lukehsiao** [comment]
Running into this same issue. This seems to be the recommended structure for asset colocation as well: https://www.getzola.org/documentation/content/overview/

**Comment by Keats** [comment]
This is weird, the https://github.com/getzola/zola/tree/master/docs/content/documentation/content directory has the same structure with the image-processing folder and it builds fine?
I probably didn't handle the root content directory properly :/

**Comment by kamoshi** [comment]
Yeah, the problem exists only specifically for the subdirectories which exist directly in content root. If there's `index.md` file in any deeper subdirectories, the website builds just fine

**Comment by Keats** [comment]
Yep I see the issue, even fixing it reveals another issue :/ 
I'm adding tests and fixing it

**Comment by Keats** [comment]
The `next` branch should fix it i think

**Comment by timharek** [comment]
When can we expect that #2103 will released @Keats?

**Comment by Keats** [comment]
Today or tomorrow, just waiting to see if there are more bugs coming up

**Comment by axwnet** [comment]
I'm still getting this error even with 0.17.2. It builds fine with 016.2.

but within a level 2 dir

**Comment by Keats** [comment]
Can you past the `tree` output or link to a repository?

**Comment by rimutaka** [comment]
I get this error in 0.19.1 after opening an old project with just one file that used to work fine.
```
- content
-- index.md
```
