### ISSUE TITLE
`zola serve` with `--output-dir` stopped serving assets in v0.18.0

### ISSUE THREAD

**Issue by radekmie** [Keats/gutenberg#2423]
# Bug Report

## Environment

Zola version: v0.18.0

## Expected Behavior
`zola serve --output-dir docs` should render the page normally, just like `zola serve` (i.e., with no custom `--output-dir`). That's how it worked in 0.17.2.

## Current Behavior
The HTML is served correctly, but all assets - including CSS and image files - result in 404.

## Step to reproduce
1. Run `zola serve`. The website looks normal.
2. Run `zola serve --output-dir docs`. The website looks broken, as the CSS is not there.

**Comment by wold5** [comment]
Can confirm this, with 0.18 for Windows. The files are actually present in the output directory, but not loaded.

Ignore the latter re Linux: I accidentally used 0.17 (system installed). This might be another issue, TBC.

**Comment by emilyalbini** [comment]
This is fixed by https://github.com/getzola/zola/pull/2398, it would be nice to have a patch release with the fix.

**Comment by Keats** [comment]
There's probably going to be a new release anyway since pulldown_cmark was updated

**Comment by maghoff** [comment]
A workaround for this problem is to give the absolute path of the output directory on the command line, ie instead of `--output-dir docs`, `--output-dir /full/path/to/docs`.

**Comment by wold5** [comment]
> A workaround for this problem is to give the absolute path of the output directory on the command line, ie instead of `--output-dir docs`, `--output-dir /full/path/to/docs`.

This didn't solve it on Windows - and I always use the full path to a ramdisk.

Current next with https://github.com/getzola/zola/pull/2398 fails to run for me on Windows, further comments will follow in that thread. 

My earlier comment re Linux can be ignored BTW. I usually write on Windows and compile on Linux. I forget `--drafts`... after a long day, when converting shortcodes to macros turned up all kinds of issues to do with scope overlap, etc, etc. (since solved) ;)

**Comment by maghoff** [comment]
@wold5 You'd need to format the path exactly like [`fs::canonicalize`](https://doc.rust-lang.org/std/fs/fn.canonicalize.html) does. I think you'd get paths that start with `\\?\` in that syntax. But I'm no Windows guru. If you need the workaround, the simplest way is probably to write a test program just to canonicalize the path correctly :)

**Comment by Keats** [comment]
Would https://crates.io/crates/normpath solve the issue?
